#!/usr/bin/env bash
# performing a 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="srrver_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/MmeliNtshakala permanenr;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enables/default

sudo service nginx restart
